<script lang="ts">
    import { page } from "$app/stores";
    export let pid: Number;
    function regeneratePID() {pid = Math.round( Math.random() * 1000000 )}

    page.subscribe(regeneratePID)
    regeneratePID()
</script>

<div id="main">
    <h1>
        {$page.status}
    </h1>
    {#if $page.status == 404}
        <p><code>site@soopy.moe$ show {$page.url.pathname}</code></p>
        <p><code>show: file or directory not found: {$page.url.pathname}</code></p>
        <p><code>site@soopy.moe [1]$ </code></p>
    {:else}
        <p><code>site@soopy.moe$ show {$page.url.pathname}</code></p>
        <pre>[1]   {pid}  segmentation fault (core dumped)  show {$page.url.pathname}</pre>
        <p><code>site@soopy.moe [139]$ coredumpctl debug {pid} -A "--batch -ex bt" -q</code></p>
        <pre>[New LWP 214063]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/run/eph/libexec/show {$page.url.pathname}'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 {$page.error?.message}
</pre>
        <p><code>site@soopy.moe$ </code></p>
    {/if}
</div>

<style lang="sass">
    h1
        margin: 0
        margin-bottom: 0.5rem

    #main
        margin: 0 1rem
</style>
